propelsoa:
  resource: "@PropelSOABundle/Resources/config/routing.yml"
  prefix: /public

training_training:
    resource: "@TrainingTrainingBundle/Resources/config/routing.yml"
    prefix:   /training
public_training_training:
    resource: "@TrainingTrainingBundle/Resources/config/publicrouting.yml"
    prefix:   /public/training
