imports:
  - { resource: "@EngineAuthBundle/Resources/config/security.yml" }

jms_security_extra:
  secure_all_services: false
  expressions: true

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Engine\AuthBundle\Model\User: sha512
    Engine\AuthBundle\Utility\PasswordUtility: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
  providers:
    main:
      propel:
        class: Engine\AuthBundle\Model\User
        property: login
  firewalls:
    public:
      pattern: ^/public.+$
      security: false
    signup:
      pattern: ^/(signup|index)$
      security: false
    auth_area:
      pattern: ^/auth/login
      authapi: true
      context: MainContext
    secured_area:
      pattern: ^/.+$
      authapi: true
      context: MainContext

  access_control:
    - { path: ^/est, roles: ROLE_ADMIN }
